version: "3"
services:
  db1:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb1
      MYSQL_USER: foodzila
      MYSQL_PASSWORD: foodzila
    volumes:
      - mydb1_data:/var/lib/mysql

    ports:
      - "3307:3306"


  db2:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb2
      MYSQL_USER: foodzila1
      MYSQL_PASSWORD: foodzila1
    volumes:
      - mydb2_data:/var/lib/mysql

    ports:
      - "3308:3306"
volumes:
  mydb1_data:
  mydb2_data:
