// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using academy_docker_demo.Data;

#nullable disable

namespace academy_docker_demo.Migrations
{
    [DbContext(typeof(FoodzillaContext))]
    [Migration("20230531081133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("academy_docker_demo.Models.Recipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Kalle",
                            Date = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Mix some stuff, cook it in the oven, enjoy!",
                            Title = "Best meal ever",
                            UserID = 0
                        },
                        new
                        {
                            ID = 2,
                            Author = "Victoria",
                            Date = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Mix some stuff, cook it in the oven, enjoy!",
                            Title = "Cupcake extravaganza",
                            UserID = 0
                        },
                        new
                        {
                            ID = 3,
                            Author = "Anna",
                            Date = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Mix some stuff, cook it in the oven, enjoy!",
                            Title = "American pancakes",
                            UserID = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
